### ISSUE TITLE
Use child_process.spawn instead of child_process.exec

### ISSUE THREAD

**Issue by vvo** [caseywebdev/watchy#10]
[child_process.exec](http://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) is designed to execute command and get a result.
It does not fits the long running processes like a web server. As watchy primilar use is to have a long running command waiting for restart, we should not use child_process.exec.

Why? Because child_process.exec has a maxBuffer value, indeed, as it's a command used to get a result most of the time.

So we should use [child_process.spawn](http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).

I uncovered this because I had a long running web server with lot of logging happening and sometimes my server would just fails and stop at some point but always after the same amount of output (maxBuffer).

@caseywebdev what do you think? Thanks.

**Comment by caseywebdev** [comment]
The original implementation used `spawn`, but we switched to `exec` because it was suggested in #2 and I wasn't aware of the `maxBuffer` dilemma. I've switched it back to `spawn` locally and it seems we can still get all the advantages of bash using `watchy -- /bin/sh -c "echo foo bar baz | grep -o foo"`. A little more to type, but at least this will alleviate `maxBuffer` issue while still allowing the current functionality. I'll push a release shortly.

**Comment by caseywebdev** [comment]
For anyone stumbling across this looking for how to do the old `exec`-ish commands (i.e. running bash code), check the README for examples.

**Comment by vvo** [comment]
@caseywebdev WOO! Amazing reactivity, thanks :)

**Comment by caseywebdev** [comment]
No prob, thanks for saying something!
