### ISSUE TITLE
--watch Spawn failed

### ISSUE THREAD

**Issue by orschiro** [caseywebdev/watchy#12]
Dear @caseywebdev,

Thank you very much for watchy! I want to use it to watch for changes of my Jekyll blog `_config.yml`. I run the command as follows:

```
 watchy -w _config.yml -- "jekyll serve --watch"
```

However, it fails with the following error:

```
[watchy] jekyll serve --watch Spawning...
[watchy] jekyll serve --watch Spawn failed (Error: spawn jekyll serve --watch ENOENT)
```

Do you have any idea why it fails?

Thanks very much ahead!

Robert

**Comment by caseywebdev** [comment]
Try removing the quotes: `watchy -w _config.yml -- jekyll serve --watch`

The latest watchy uses spawn instead of exec. With the quotes there, spawn is trying to execute the file `jekyll serve --watch` which obviously doesn't exist. Without the quotes, it will execute `jekyll` with the `serve --watch` arguments.

**Comment by orschiro** [comment]
@caseywebdev 

Yes, without quotes works perfectly. Thank you very much!

**Comment by deathmood** [comment]
@caseywebdev have same issue on windows. I try to run `watchy --watch scss -- npm run aaa`
and each time have output 
```
2016-03-08T12:14:54.805Z [npm] INFO Spawning...
2016-03-08T12:14:54.819Z [npm] ERROR Spawn failed (Error: spawn npm ENOENT)
```

same happens even if I run `watchy --watch scss -- echo hi!`

**Comment by deathmood** [comment]
it works if I write like this 
```
watchy -w scss -- cmd /c \"npm run aaa\"
```

but that makes script platform-dependent
